services:
  pokemon-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"  
    volumes:
      - pokemon_pgdata:/var/lib/postgresql/data
      - ./create-pokemon-schema.sql:/docker-entrypoint-initdb.d/create-pokemon-schema.sql:ro

volumes:
  pokemon_pgdata:
